### ISSUE TITLE
Just a note

### ISSUE THREAD

**Issue by benadamstyles** [nielsenramon/duotone-snow#1]
to say I really love this theme, it's the first "light" theme I've found to be comfortable to use, so thanks very much. Do you have any plans to make a "dark" version? I like to switch at night to a dark one and I like the colours you've chosen a lot.

**Comment by nielsenramon** [comment]
@Leeds-eBooks Thanks! I suppose I could create a dark theme with these colors. I'll see if it looks good and let you know :)

**Comment by benadamstyles** [comment]
Great! That would be fantastic. Let me know if I can help in any way.
